version: '3'

volumes:
  exec_data:

services:
  redis:
    image: redis:6.2.6
    command: --port 5050
    ports:
      - "5050:5050"
    networks:
      - default
  policy-handler:
    image: planqk/policy-handler:local
    command: sh /startup.sh
    ports:
      - "8892:8892"
    environment:
      - FLASK_RUN_HOST=policy-handler
      - FLASK_RUN_PORT=8892
      - REDIS_URL=redis://redis:5050
      - DATABASE_URL=sqlite:////data/app.db
    volumes:
      - exec_data:/data
    networks:
      - default
  rq-worker:
    image: planqk/policy-handler:local
    command: rq worker --url redis://redis:5050 policy-handler
    environment:
      - FLASK_RUN_HOST=policy-handler
      - FLASK_RUN_PORT=8892
      - REDIS_URL=redis://redis:5050
      - DATABASE_URL=sqlite:////data/app.db
    volumes:
      - exec_data:/data
    depends_on:
      - redis
    deploy:
      replicas: 1
    networks:
      - default
networks:
  default:
    driver: bridge
